#!/bin/sh

docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.1-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^11" -n -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.1-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^12" -q -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.2-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^11" -q -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.2-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^12" -q -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.3-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^11" -q -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.3-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^12" -q -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.3-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^13" -q -n -W && vendor/bin/grumphp run && composer test'
docker run --rm --entrypoint= -v ./:/app --tmpfs /app/public --tmpfs /app/vendor,mode=1777 --tmpfs /app/var -v ~/.composer/cache/:/home/application/.composer/cache/ -w /app ghcr.io/pluswerk/php-dev:nginx-8.4-alpine bash -c 'git config --global --add safe.directory /app && composer update --with typo3/minimal="^13" -q -n -W && vendor/bin/grumphp run && composer test'
